
global record RuneTypes
    enum RuneMethodNames
        "end_of_turn_effect"
        "owner_modify_damage"
        "owner_modify_speed"
     end
     record Rune
        --[[
        {RuneMethodNames:function(Rune,any,any,any)}
        end_of_turn_effect: function(Rune, any, any,any)
        owner_modify_damage:function(Rune, any, any,any)
        owner_modify_speed: function(Rune, any, any,any)
        --]]
        bla:NOTHIONG 
     end
end
return RuneTypes