[package]
name = "card_game"
version = "0.1.0"
authors = ["lenscas <lenscas@gmail.com>"]
edition = "2018"

[[bin]]
name = "teal_generator"
test = false
bench = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.21", features = ["macros","fs","stream"] }
warp = "*"
sqlx = { version = "0.4.0", default-features = false, features = [ "runtime-tokio", "macros", "postgres", "offline", "json" ] }
dotenv = "*"
futures = "*"
serde = {version="1.0", features=["derive"]}
serde_json = "*"
argonautica = "*"
rand_core="*"
rand = "*"
sha2 = "*"
base64 = "*"
http = "0.2.0"
rlua = "*"
card_game_shared = {path="../shared", features=["server"]}
pretty_env_logger = "*"
tealr = {version = "0.2.0"}
#card_game_shared = {path="../card_game_shared", features=["server"]}

[profile.dev.package."*"]
opt-level = 3