name: Tests
on:
  pull_request:
    paths:
      - '**/src/**.r'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/CI.yml'
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
        components: rustfmt
    - name: Formatting check
      run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1.3.4 
      with:
        rust-version: stable
        components: clippy
    - uses: actions/checkout@master
    - name: Clippy
      run: cargo clippy -- -D warnings
