name: Tests
on:
  pull_request:
    paths:
      - '**/src/**.r'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/CI.yml'
jobs:
  formatting_server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
        components: rustfmt
    - name: cargo fmt
      run: cd server && cargo fmt --all -- --check

  clippy_server:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1.3.4 
      with:
        rust-version: stable
        components: clippy
    - uses: actions/checkout@master
    - name: cargo clippy
      run: cd server && cargo clippy -- -D warnings
  
  formatting_shared:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
        components: rustfmt
    - name: cargo fmt
      run: cd shared && cargo fmt --all -- --check
  
  clippy_shared:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1.3.4 
      with:
        rust-version: stable
        components: clippy
    - uses: actions/checkout@master
    - name: cargo clippy
      run: cd shared && cargo clippy -- -D warnings
